[package]
name = "lisp"
version = "0.0.1"
edition = "2021"

[dependencies]
laps = { version = "0.1.3", features = ["macros"] }
sigma_vm = { path = "../sigma_vm", version = "0.0.2" }
clap = { version = "4.3.21", features = ["derive"] }
